"""
server.py — Local web portal backend for Job Auto Apply Bot
Run: python server.py  then open http://localhost:5000
"""

import os
import sys
import json
import csv
import subprocess
import threading
import datetime
from flask import Flask, render_template, jsonify, request, send_from_directory

os.chdir(os.path.dirname(os.path.abspath(__file__)))

app = Flask(__name__, static_folder="portal/static", template_folder="portal")

running_bots = {}
bot_logs = {}


def read_profile():
    try:
        if "config.profile" in sys.modules:
            del sys.modules["config.profile"]
        if "config" in sys.modules:
            del sys.modules["config"]
        from config.profile import (
            PROFILE, MY_SKILLS, SEARCH_KEYWORDS, SEARCH_LOCATIONS, TARGET_COMPANIES,
            MIN_MATCH_SCORE, TECH_EXPERIENCE, WORK_PREFERENCES, SALARY_KEYWORDS, COVER_LETTER
        )
        return {
            "profile": PROFILE,
            "skills": MY_SKILLS,
            "search_keywords": SEARCH_KEYWORDS,
            "search_locations": SEARCH_LOCATIONS,
            "target_companies": TARGET_COMPANIES,
            "min_match_score": MIN_MATCH_SCORE,
            "tech_experience": TECH_EXPERIENCE,
            "work_preferences": WORK_PREFERENCES,
            "salary_keywords": SALARY_KEYWORDS,
            "cover_letter": COVER_LETTER
        }
    except Exception as e:
        return {"error": str(e)}


def write_profile(data):
    current = read_profile()
    if "error" in current:
        current = {}

    profile = data.get("profile", current.get("profile", {}))
    skills = data.get("skills", current.get("skills", []))
    keywords = data.get("search_keywords", current.get("search_keywords", []))
    locations = data.get("search_locations", current.get("search_locations", []))
    targets = data.get("target_companies", current.get("target_companies", []))
    min_score = data.get("min_match_score", current.get("min_match_score", 30))
    tech_exp = data.get("tech_experience", current.get("tech_experience", {}))
    work_prefs = data.get("work_preferences", current.get("work_preferences", {}))
    salary_kws = data.get("salary_keywords", current.get("salary_keywords", []))
    cover_letter = data.get("cover_letter", current.get("cover_letter", ""))

    skills_str = ",\n    ".join([f'"{s}"' for s in skills])
    keywords_str = ",\n    ".join([f'"{k}"' for k in keywords])
    locations_str = ",\n    ".join([f'"{l}"' for l in locations])
    targets_str = ", ".join([f'"{t}"' for t in targets])
    salary_kws_str = ", ".join([f'"{s}"' for s in salary_kws])

    tech_exp_lines = []
    for k, v in tech_exp.items():
        tech_exp_lines.append(f'    "{k}": "{v}",')
    tech_exp_str = "\n".join(tech_exp_lines)

    work_prefs_lines = []
    for k, v in work_prefs.items():
        if isinstance(v, bool):
            val_str = "True" if v else "False"
        else:
            val_str = f'"{v}"'
        work_prefs_lines.append(f'    "{k}": {val_str},')
    work_prefs_str = "\n".join(work_prefs_lines)

    content = f'''# Auto-generated by Job Bot Portal
PROFILE = {{
    "first_name":   "{profile.get("first_name", "")}",
    "last_name":    "{profile.get("last_name", "")}",
    "email":        "{profile.get("email", "")}",
    "phone":        "{profile.get("phone", "")}",
    "city":         "{profile.get("city", "")}",
    "state":        "{profile.get("state", "")}",
    "country":      "{profile.get("country", "India")}",
    "linkedin_url": "{profile.get("linkedin_url", "")}",
    "github_url":   "{profile.get("github_url", "")}",
    "total_experience_years": "{profile.get("total_experience_years", "5")}",
    "current_ctc":            "{profile.get("current_ctc", "")}",
    "expected_ctc":           "{profile.get("expected_ctc", "")}",
    "notice_period":          "{profile.get("notice_period", "30")}",
    "resume_path": r"{profile.get("resume_path", "")}",
    "linkedin_email":    "{profile.get("linkedin_email", "")}",
    "linkedin_password": "{profile.get("linkedin_password", "")}",
    "naukri_email":    "{profile.get("naukri_email", "")}",
    "naukri_password": "{profile.get("naukri_password", "")}",
}}

MY_SKILLS = [
    {skills_str}
]

MIN_MATCH_SCORE = {min_score}

SEARCH_KEYWORDS = [
    {keywords_str}
]

SEARCH_LOCATIONS = [
    {locations_str}
]

TARGET_COMPANIES = [{targets_str}]

TECH_EXPERIENCE = {{
{tech_exp_str}
}}

WORK_PREFERENCES = {{
{work_prefs_str}
}}

SALARY_KEYWORDS = [{salary_kws_str}]

COVER_LETTER = """{cover_letter}""".strip()
'''
    with open("config/profile.py", "w", encoding="utf-8") as f:
        f.write(content)
    return True


def get_applications():
    tracker_path = os.path.join(os.getcwd(), "logs", "job_applications.csv")
    if not os.path.exists(tracker_path):
        return []
    rows = []
    try:
        with open(tracker_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(dict(row))
    except Exception:
        pass
    return list(reversed(rows))


def get_stats():
    apps = get_applications()
    total = len(apps)
    applied = sum(1 for a in apps if a.get("Status") == "Applied")
    skipped = sum(1 for a in apps if a.get("Status") == "Skipped")
    manual = sum(1 for a in apps if a.get("Status") == "Manual Needed")
    today = datetime.date.today().strftime("%Y-%m-%d")
    today_count = sum(1 for a in apps if a.get("Date", "").startswith(today))
    portals = {}
    for a in apps:
        p = a.get("Portal", "Other")
        portals[p] = portals.get(p, 0) + 1
    return {
        "total": total, "applied": applied, "skipped": skipped,
        "manual": manual, "today": today_count, "portals": portals,
    }


def stream_bot(bot_key, cmd):
    bot_logs[bot_key] = []
    running_bots[bot_key] = True
    try:
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace", cwd=os.getcwd()
        )
        for line in proc.stdout:
            bot_logs[bot_key].append(line.rstrip())
        proc.wait()
    except Exception as e:
        bot_logs[bot_key].append(f"[ERROR] {e}")
    finally:
        running_bots[bot_key] = False


@app.route("/")
def index():
    return send_from_directory("portal", "index.html")


@app.route("/api/profile", methods=["GET"])
def api_get_profile():
    return jsonify(read_profile())


@app.route("/api/profile", methods=["POST"])
def api_save_profile():
    data = request.json
    try:
        write_profile(data)
        return jsonify({"success": True, "message": "Profile saved!"})
    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 500


@app.route("/api/applications")
def api_applications():
    return jsonify(get_applications())


@app.route("/api/stats")
def api_stats():
    return jsonify(get_stats())


@app.route("/api/review_queue")
def api_review_queue():
    import tracker
    return jsonify(tracker.get_review_queue())


@app.route("/api/review/approve", methods=["POST"])
def api_review_approve():
    import tracker
    data = request.json or {}
    url = data.get("url")
    if not url:
        return jsonify({"success": False, "message": "Missing URL"}), 400
    res = tracker.approve_review_job(url)
    return jsonify({"success": res})


@app.route("/api/review/reject", methods=["POST"])
def api_review_reject():
    import tracker
    data = request.json or {}
    url = data.get("url")
    if not url:
        return jsonify({"success": False, "message": "Missing URL"}), 400
    res = tracker.reject_review_job(url)
    return jsonify({"success": res})


@app.route("/api/bot/start", methods=["POST"])
def api_start_bot():
    data = request.json
    platform = data.get("platform", "all")
    company = data.get("company", "")
    headless = data.get("headless", False)

    bot_key = platform
    if running_bots.get(bot_key):
        return jsonify({"success": False, "message": f"{platform} bot is already running!"})

    if platform == "all":
        cmd = [sys.executable, "main.py"]
    else:
        cmd = [sys.executable, "main.py", f"--{platform}"]

    if headless:
        cmd.append("--headless")
    if company:
        cmd += ["--company", company]

    thread = threading.Thread(target=stream_bot, args=(bot_key, cmd), daemon=True)
    thread.start()
    return jsonify({"success": True, "message": f"{platform.title()} bot started!", "key": bot_key})


@app.route("/api/bot/logs/<bot_key>")
def api_bot_logs(bot_key):
    offset = int(request.args.get("offset", 0))
    logs = bot_logs.get(bot_key, [])
    return jsonify({
        "running": running_bots.get(bot_key, False),
        "logs": logs[offset:],
        "total": len(logs),
    })


import time

connection_status = {
    "linkedin": {"status": "Disconnected", "message": ""},
    "naukri":   {"status": "Disconnected", "message": ""}
}

# Keep driver handles alive during challenge resolution so user can solve OTP in browser
_active_drivers = {}


def test_connection_worker(platform):
    connection_status[platform] = {"status": "Checking", "message": "Launching browser..."}

    # Close any previously open driver for this platform
    if platform in _active_drivers:
        try:
            _active_drivers[platform].quit()
        except Exception:
            pass
        del _active_drivers[platform]

    driver = None
    try:
        # Reload profile fresh from disk to pick up latest saved credentials
        import importlib, sys
        for mod in list(sys.modules.keys()):
            if "config" in mod:
                del sys.modules[mod]
        from config.profile import PROFILE

        from browser import create_browser, fill, click, human_pause
        from selenium.webdriver.common.by import By

        connection_status[platform] = {"status": "Checking", "message": "Starting Chrome browser..."}
        driver = create_browser(headless=False)
        _active_drivers[platform] = driver

        # ── LinkedIn ──────────────────────────────────────────────────────────
        if platform == "linkedin":
            connection_status[platform] = {"status": "Checking", "message": "Opening LinkedIn login page..."}
            driver.get("https://www.linkedin.com/login")
            human_pause(2, 4)

            connection_status[platform] = {"status": "Checking", "message": "Entering credentials..."}
            filled_user = fill(driver, By.ID, "username", PROFILE["linkedin_email"])
            filled_pass = fill(driver, By.ID, "password", PROFILE["linkedin_password"])

            if not filled_user or not filled_pass:
                connection_status[platform] = {"status": "Failed", "message": "Could not find LinkedIn login form. Page may have changed."}
                return

            clicked = click(driver, By.XPATH, "//button[@type='submit']")
            if not clicked:
                # Try alternate button
                click(driver, By.CSS_SELECTOR, "button.btn__primary--large")

            connection_status[platform] = {"status": "Checking", "message": "Waiting for LinkedIn to respond..."}

            # Poll up to 90 seconds (18 x 5s) — enough time to solve 2FA manually
            for check in range(18):
                time.sleep(5)
                try:
                    current_url = driver.current_url
                except Exception:
                    break

                if any(x in current_url for x in ["feed", "mynetwork", "jobs", "messaging", "home"]):
                    connection_status[platform] = {"status": "Connected", "message": "LinkedIn login successful!"}
                    return
                elif any(x in current_url for x in ["checkpoint", "challenge", "two-step", "security-verification", "pin", "phone"]):
                    connection_status[platform] = {
                        "status": "Challenge Required",
                        "message": "OTP / 2FA / CAPTCHA shown in Chrome. Please complete it manually — the portal will update automatically."
                    }
                    # Keep polling — don't break, user is solving it
                elif "login" not in current_url and "linkedin.com" in current_url:
                    # We are somewhere on LinkedIn but not login page — likely logged in
                    connection_status[platform] = {"status": "Connected", "message": "LinkedIn login successful!"}
                    return
                else:
                    connection_status[platform] = {
                        "status": "Checking",
                        "message": f"Waiting for redirect... ({(check+1)*5}s)"
                    }

            # Final check after loop
            try:
                current_url = driver.current_url
                if any(x in current_url for x in ["feed", "mynetwork", "jobs", "messaging"]):
                    connection_status[platform] = {"status": "Connected", "message": "LinkedIn login successful!"}
                else:
                    connection_status[platform] = {
                        "status": "Failed",
                        "message": f"Login timed out. Last URL: {current_url[:80]}. Check credentials or solve any verification shown in Chrome."
                    }
            except Exception:
                connection_status[platform] = {"status": "Failed", "message": "Browser closed unexpectedly."}

        # ── Naukri ────────────────────────────────────────────────────────────
        elif platform == "naukri":
            connection_status[platform] = {"status": "Checking", "message": "Opening Naukri login page..."}
            driver.get("https://www.naukri.com/nlogin/login")
            human_pause(2, 4)

            connection_status[platform] = {"status": "Checking", "message": "Entering credentials..."}

            # Naukri uses different IDs on different page loads — try both
            filled_user = (
                fill(driver, By.ID, "usernameField", PROFILE["naukri_email"]) or
                fill(driver, By.NAME, "username", PROFILE["naukri_email"]) or
                fill(driver, By.CSS_SELECTOR, "input[type='email']", PROFILE["naukri_email"])
            )
            filled_pass = (
                fill(driver, By.ID, "passwordField", PROFILE["naukri_password"]) or
                fill(driver, By.NAME, "password", PROFILE["naukri_password"]) or
                fill(driver, By.CSS_SELECTOR, "input[type='password']", PROFILE["naukri_password"])
            )

            if not filled_user or not filled_pass:
                connection_status[platform] = {"status": "Failed", "message": "Could not find Naukri login form. Page may have changed."}
                return

            clicked = (
                click(driver, By.XPATH, "//button[contains(text(),'Login')]") or
                click(driver, By.CSS_SELECTOR, "button[type='submit']") or
                click(driver, By.XPATH, "//button[contains(@class,'loginButton')]")
            )

            connection_status[platform] = {"status": "Checking", "message": "Waiting for Naukri to respond..."}

            for check in range(18):
                time.sleep(5)
                try:
                    current_url = driver.current_url
                except Exception:
                    break

                if "naukri.com" in current_url and not any(x in current_url for x in ["login", "nlogin"]):
                    connection_status[platform] = {"status": "Connected", "message": "Naukri login successful!"}
                    return
                elif any(x in current_url for x in ["captcha", "verification", "otp", "verify"]):
                    connection_status[platform] = {
                        "status": "Challenge Required",
                        "message": "OTP / CAPTCHA shown in Chrome. Please complete it manually — the portal will update automatically."
                    }
                else:
                    connection_status[platform] = {
                        "status": "Checking",
                        "message": f"Waiting for redirect... ({(check+1)*5}s)"
                    }

            try:
                current_url = driver.current_url
                if "naukri.com" in current_url and "login" not in current_url:
                    connection_status[platform] = {"status": "Connected", "message": "Naukri login successful!"}
                else:
                    connection_status[platform] = {
                        "status": "Failed",
                        "message": f"Login timed out. Last URL: {current_url[:80]}. Check credentials or solve any verification shown in Chrome."
                    }
            except Exception:
                connection_status[platform] = {"status": "Failed", "message": "Browser closed unexpectedly."}

    except Exception as e:
        import traceback
        err = traceback.format_exc()
        connection_status[platform] = {"status": "Failed", "message": f"Error: {str(e)[:200]}"}
        print(f"[CONNECTION ERROR] {platform}: {err}")
    finally:
        # Close browser only if not in challenge state
        if driver and connection_status[platform]["status"] not in ["Challenge Required", "Connected"]:
            try:
                driver.quit()
            except Exception:
                pass
            _active_drivers.pop(platform, None)


@app.route("/api/connection/test", methods=["POST"])
def api_test_connection():
    data = request.json or {}
    platform = data.get("platform")
    if platform not in ["linkedin", "naukri"]:
        return jsonify({"success": False, "message": "Invalid platform"}), 400

    if connection_status.get(platform, {}).get("status") == "Checking":
        return jsonify({"success": False, "message": f"{platform.title()} connection check is already running..."})

    thread = threading.Thread(target=test_connection_worker, args=(platform,), daemon=True)
    thread.start()
    return jsonify({"success": True, "message": f"Chrome is launching for {platform.title()} login..."})


@app.route("/api/connection/close", methods=["POST"])
def api_close_connection_browser():
    """Close any lingering browser windows opened for connection testing."""
    data = request.json or {}
    platform = data.get("platform")
    if platform and platform in _active_drivers:
        try:
            _active_drivers[platform].quit()
        except Exception:
            pass
        _active_drivers.pop(platform, None)
    return jsonify({"success": True})


@app.route("/api/connection/status")
def api_connection_status():
    return jsonify(connection_status)


@app.route("/api/bot/status")
def api_bot_status():
    return jsonify({"running": {k: v for k, v in running_bots.items()}})


if __name__ == "__main__":
    os.makedirs("logs", exist_ok=True)
    os.makedirs("portal/static", exist_ok=True)
    print("=" * 50)
    print("  Job Bot Portal is running!")
    print("  Open: http://localhost:5000")
    print("=" * 50)
    app.run(host="0.0.0.0", port=5000, debug=False)
